"""add enterprise security models and user fields

Revision ID: 248e00d23ec9
Revises: 479a77e75808
Create Date: 2026-02-18 16:20:15.210624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248e00d23ec9'
down_revision = '479a77e75808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('login_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_logs_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twofa_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('twofa_secret', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('login_attempts')
        batch_op.drop_column('twofa_secret')
        batch_op.drop_column('twofa_enabled')

    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_logs_timestamp'))

    op.drop_table('login_logs')
    with op.batch_alter_table('admin_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_logs_timestamp'))

    op.drop_table('admin_logs')
    # ### end Alembic commands ###
