"""add system settings table

Revision ID: 479a77e75808
Revises: 2f0729459f4b
Create Date: 2026-02-18 16:10:43.349598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479a77e75808'
down_revision = '2f0729459f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(length=100), nullable=True),
    sa.Column('email_sender', sa.String(length=150), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('api_rate_limit', sa.Integer(), nullable=True),
    sa.Column('max_upload_size', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
